services:

  # ─── База данни ───────────────────────────────────────────
  db:
    image: postgres:16
    container_name: survey_db
    restart: unless-stopped
    environment:
      POSTGRES_DB_FILE: /run/secrets/db_name
      POSTGRES_USER_FILE: /run/secrets/db_user
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
    secrets:
      - db_name
      - db_user
      - db_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/src/main/resources/db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - db_net

  # ─── Spring Boot Backend ──────────────────────────────────
  backend:
    image: sociologbg2-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: survey_backend
    restart: unless-stopped
    secrets:
      - db_name
      - db_user
      - db_password
      - jwt_secret
      - vote_hash_pepper
      - anthropic_api_key
      - google_client_id
    volumes:
      - ./uploads:/app/uploads
    depends_on:
      - db
    networks:
      - db_net
      - backend_net


  # ─── Next.js Frontend ─────────────────────────────────────
  frontend:
    image: sociologbg2-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_GOOGLE_CLIENT_ID: 746195861460-ecupldss51rq20dkgb65svs3i83brl54.apps.googleusercontent.com
        NEXT_PUBLIC_API_URL: https://sociolog.online
    container_name: survey_frontend
    restart: unless-stopped
    environment:
      NEXT_PUBLIC_API_URL: https://sociolog.online
      NEXTAUTH_URL: https://sociolog.bg
    secrets:
      - nextauth_secret
      - google_client_id
      - google_client_secret
      - resend_api_key
    depends_on:
      - backend
    networks:
      - backend_net
      - public_net

  # ─── Nginx ─────────────────────────────────────
  nginx:
    image: nginx:alpine
    container_name: survey_nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - ./uploads:/srv/uploads:ro
    depends_on:
      - frontend
      - backend
    networks:
      - public_net
      - backend_net

volumes:
  postgres_data:

networks:
  public_net:
  backend_net:
  db_net:
      internal: true

secrets:
  db_name:
    external: true
  db_user:
    external: true
  db_password:
    external: true
  jwt_secret:
    external: true
  google_client_secret:
    external: true
  anthropic_api_key:
    external: true
  resend_api_key:
    external: true
  google_client_id:
    external: true
  vote_hash_pepper:
    external: true
  nextauth_secret:
    external: true
